electronics-app/overlays/qa/platform-deploy.yaml
=> rebuild_qa

electronics-app/overlays/qa/modules.json, electronics-app/overlays/qa/platform-deploy.yaml
=> qa_electronic

apps-config/base/electronics-app.yaml, electronics-app/overlays/qa/kustomization.yaml, electronics-app/overlays/qa/modules.json
Platform:  newTag: 3.4.0-d77bdec4
Storefront: newTag: 5.0.0-d666b094
Added Module: VirtoCommerce.DynamicAssociationsModule_3.1.0.zip
=> rebuild_qa_env

webstore-app/overlays/qa/modules.json, webstore-app/overlays/qa/platform-deploy.yaml
Added DemoSolutionFeatures module to QA environment
=> VP-4656: Add DemoSolutionFeatures module

webstore-app/overlays/qa/kustomization.yaml, webstore-app/overlays/qa/modules.json, webstore-app/overlays/qa/platform-deploy.yaml
Delivery on QA: VP-4693, VP-1214, VP-4521, VP-4538, VP-4651
=> VP-4693, VP-1214, VP-4521, VP-4538, VP-4651

webstore-app/overlays/qa/cms-content-cm.yaml, webstore-app/overlays/qa/deployment-cm.yaml, webstore-app/overlays/qa/kustomization.yaml, webstore-app/overlays/qa/platform-deploy.yaml
- Add redis service 
- Change platform init image and script for upload assets
- Add configmap for env
- Auto reloader deployment when configmap changes
=> VP-4553: Change configuration

webstore-app/overlays/qa/deployment-cm.yaml
Fix Theme is rendered incorrectly on safari
=> VP-4853: Theme is rendered incorrectly on safari

webstore-app/overlays/qa/deployment-cm.yaml
VP-4624: Fix purchase order style & notification
=> VP-4624: Fix purchase order style & notification

webstore-app/overlays/qa/environment-cm.yaml, webstore-app/overlays/qa/kustomization.yaml, webstore-app/overlays/qa/platform-deploy.yaml, webstore-app/overlays/qa/storefront-deploy.yaml
=> VP-4975: Notifications config using vault secrets

webstore-app/overlays/qa/deployment-cm.yaml
VP-4643: Product details page redesign.
=> VP-4643: Product details page redesign

webstore-app/overlays/qa/deployment-cm.yaml
=> Delivery updates for

public-app/overlays/demo/error-page.yaml, public-app/overlays/demo/ingress.yaml, public-app/overlays/demo/kube-job.yaml, public-app/overlays/demo/kustomization.yaml, public-app/overlays/demo/platform-cm.yaml, public-app/overlays/demo/platform-deploy.yaml, public-app/overlays/demo/storefront-cm.yaml, public-app/overlays/demo/storefront-deploy.yaml
New configuration for refreshing public demo
=> VP-5039: The Public Demo

webstore-app/overlays/demo/platform-cm.yaml, webstore-app/overlays/demo/platform-deploy.yaml
Demo solution sso with azure ad.
=> VP-5094 demo solution to azure ad.

webstore-app/overlays/qa/cert-manager/platform-cert.yaml, webstore-app/overlays/qa/cert-manager/platform-issuer.yaml, webstore-app/overlays/qa/cert-manager/storefront-cert.yaml, webstore-app/overlays/qa/cert-manager/storefront-issuer.yaml, webstore-app/overlays/qa/ingress.yaml, webstore-app/overlays/qa/kustomization.yaml, webstore-app/overlays/qa/traefik/ingress-traefik.yaml, webstore-app/overlays/qa/traefik/middleware-redirect.yaml
Add https support with Traefik ingress
Add certificate with cert-manager
=> VP-5174: Traefik https and cert-manager

webstore-app/overlays/qa/deployment-cm.yaml
DoD:
Home: Virto Commerce Demo B2B Online Shopping for you - B2B Store
Category:  Virto Commerce Demo B2B Online Shopping for {Category Name} - B2B Store
Product:  Virto Commerce Demo B2B Online Shopping for {Product Name} - B2B Store
Cart: Virto Commerce Demo B2B Cart - B2B Store
My Account: Virto Commerce Demo B2B My Account - B2B Store
Other/Default: Virto Commerce Demo B2B Online Shopping for you - B2B Store
=> VP-5619: Improve B2B store pages titles

webstore-app/overlays/qa/deployment-cm.yaml
Customers segment functionality was extracted to separate module.
id: VirtoCommerce.DemoCustomerSegmentsModule
=> VDS-175 Update modules. 

regression-app/overlays/qa/platform-cm.yaml, webstore-app/overlays/qa/platform-cm.yaml
Fix error with install license key
=> VC-5785: Change private key path

webstore-app/overlays/qa/deployment-cm.yaml
View ixisted segments.
Add/Edit segment
Delete segment.
Without index job.
Stories: VDS-16, VDS-17, VDS-12
=> Stories: VDS-16, VDS-17, VDS-12; Tasks: VDS-332, VDS-333, VDS-334, VDS-368

webstore-app/overlays/demo/deployment-cm.yaml
=> VDS-382: Fix customer segments preview & property value validation

webstore-app/overlays/qa/kustomization.yaml, webstore-app/overlays/qa/traefik/ingress-https.yaml, webstore-app/overlays/qa/traefik/ingress.yaml, webstore-app/overlays/qa/traefik/middleware-retry.yaml
Add a middleware that will repeat unsuccessful requests 3 times
=> VP-6409: Add retry middleware

webstore-app/overlays/qa/deployment-cm.yaml
=> VDS-410, VDS-411 Create configurable product

webstore-app/overlays/qa/deployment-cm.yaml
To test it you will needed sample data created through API. Please let me know, when this PR will be merged & QA will be updated
=> VDS-512: View configuration parts of product

webstore-app/overlays/qa/deployment-cm.yaml
=> VDS-54, VDS-60: Fix erros in b2b theme with the shiiping amount in cart and order summary.

webstore-app/overlays/qa/deployment-cm.yaml
=> VDS-109: Fix links to user lists

webstore-app/overlays/qa/deployment-cm.yaml
=> VDS-58: Fix error. Cart icon not updated on Complete page of the checkout

webstore-app/overlays/qa/deployment-cm.yaml
Also disable add to cart button if qty == 0
=> VDS-200, VDS-79  Fix errors with qty input in the cart. 

webstore-app/overlays/qa/deployment-cm.yaml
=> VDS-200: Fix error with undefined qty at adding to cart

webstore-app/overlays/qa/deployment-cm.yaml, webstore-app/overlays/qa/kustomization.yaml
Old password checking
Password updating
Success alert
Errors showing
=> VDS-74: Fix errors with changing user password

regression-app/overlays/qa/kustomization.yaml, regression-app/overlays/qa/platform-cm.yaml, regression-app/overlays/qa/platform-deploy.yaml, regression-app/overlays/qa/shared-pvc.yaml
VP-6349: Add shared volume for license
VP-6386: Add shared export folder
=> VP-6349: Add shared volume
